version: "3.9"

services:
  app:
    build:
      args:
        user: appuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: symfony
    container_name: symfony-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - symfony
  db:
    image: mysql:5.7
    container_name: symfony-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - symfony
    ports:
      - 3306:3306 # expose db to remote services like workbench
  nginx:
    image: nginx:1.17-alpine
    container_name: symfony-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
